# Generated by Django 3.0.7 on 2020-06-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=40)),
                ('item_name', models.CharField(max_length=100)),
                ('item_category', models.CharField(max_length=100)),
                ('sub_cat', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'Data',
            },
        ),
    ]
