# Generated by Django 3.0.8 on 2020-07-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
