# Generated by Django 3.0.8 on 2020-07-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
