# Generated by Django 3.0.8 on 2020-07-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='add_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(),
        ),
    ]
