# Generated by Django 3.0.8 on 2020-07-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20200710_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pid',
            field=models.CharField(max_length=100),
        ),
    ]
