# Generated by Django 3.0.8 on 2020-07-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20200710_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
