# Generated by Django 3.0.8 on 2020-07-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20200710_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('total', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('items', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
