# Generated by Django 3.0.8 on 2020-07-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
