# Generated by Django 3.0.8 on 2020-07-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20200711_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
