# Generated by Django 3.0.8 on 2020-07-10 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_auto_20200711_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='cust_name',
            new_name='name',
        ),
    ]
