# Generated by Django 3.0.8 on 2020-07-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_auto_20200711_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdata',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
