# Generated by Django 3.0.8 on 2020-07-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_auto_20200712_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('stock_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stock_from', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('items', models.IntegerField()),
            ],
        ),
    ]
