# Generated by Django 3.0.8 on 2020-07-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_date',
            field=models.DateTimeField(default=2),
            preserve_default=False,
        ),
    ]
