# Generated by Django 3.0.8 on 2020-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_stock_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
