# Generated by Django 3.0.8 on 2020-07-28 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_remove_stock_stock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
