# Generated by Django 3.0.8 on 2020-07-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_stock_stock_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stock_date',
            new_name='date',
        ),
    ]
