# Generated by Django 3.0.8 on 2020-07-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_auto_20200728_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
    ]
