# Generated by Django 3.0.8 on 2020-07-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0028_stock_stock_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stock',
        ),
    ]
