# Generated by Django 3.0.8 on 2020-07-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0029_delete_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_mgt',
            fields=[
                ('stock_num', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stock_date', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('Desti', models.CharField(max_length=100)),
                ('items', models.CharField(max_length=100)),
            ],
        ),
    ]
