# Generated by Django 3.0.8 on 2020-07-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0030_stock_mgt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stock_mgt',
        ),
    ]
